# Generated by Django 5.0.9 on 2024-12-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionContent',
            new_name='Content',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id'], 'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Test description')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=40, null=True, verbose_name='Answer')),
                ('test_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Test section')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['test_section'],
            },
        ),
    ]
